starter = "https://github.com/LazyVim/starter"

plugins = [
  "https://github.com/goolord/alpha-nvim.git",
  "https://github.com/akinsho/bufferline.nvim.git",
  "https://github.com/hrsh7th/cmp-buffer.git",
  "https://github.com/saadparwaiz1/cmp_luasnip.git",
  "https://github.com/hrsh7th/cmp-nvim-lsp.git",
  "https://github.com/hrsh7th/cmp-path.git",
  "https://github.com/stevearc/dressing.nvim.git",
  "https://github.com/ggandor/flit.nvim.git",
  "https://github.com/rafamadriz/friendly-snippets.git",
  "https://github.com/lewis6991/gitsigns.nvim.git",
  "https://github.com/lukas-reineke/indent-blankline.nvim.git",
  "https://github.com/folke/lazy.nvim.git",
  "https://github.com/LazyVim/LazyVim.git",
  "https://github.com/ggandor/leap.nvim.git",
  "https://github.com/nvim-lualine/lualine.nvim.git",
  "https://github.com/L3MON4D3/LuaSnip.git",
  "https://github.com/williamboman/mason-lspconfig.nvim.git",
  "https://github.com/williamboman/mason.nvim.git",
  "https://github.com/echasnovski/mini.ai.git",
  "https://github.com/echasnovski/mini.bufremove.git",
  "https://github.com/echasnovski/mini.comment.git",
  "https://github.com/echasnovski/mini.indentscope.git",
  "https://github.com/echasnovski/mini.pairs.git",
  "https://github.com/echasnovski/mini.surround.git",
  "https://github.com/folke/neoconf.nvim.git",
  "https://github.com/folke/neodev.nvim.git",
  "https://github.com/nvim-neo-tree/neo-tree.nvim.git",
  "https://github.com/folke/noice.nvim.git",
  "https://github.com/MunifTanjim/nui.nvim.git",
  "https://github.com/jose-elias-alvarez/null-ls.nvim.git",
  "https://github.com/catppuccin/nvim.git/",
  "https://github.com/hrsh7th/nvim-cmp.git",
  "https://github.com/neovim/nvim-lspconfig.git",
  "https://github.com/SmiteshP/nvim-navic.git",
  "https://github.com/rcarriga/nvim-notify.git",
  "https://github.com/windwp/nvim-spectre.git",
  "https://github.com/nvim-treesitter/nvim-treesitter.git",
  "https://github.com/nvim-treesitter/nvim-treesitter-textobjects.git",
  "https://github.com/JoosepAlviste/nvim-ts-context-commentstring.git",
  "https://github.com/nvim-tree/nvim-web-devicons.git",
  "https://github.com/folke/persistence.nvim.git",
  "https://github.com/nvim-lua/plenary.nvim.git",
  "https://github.com/nvim-telescope/telescope.nvim.git",
  "https://github.com/folke/todo-comments.nvim.git",
  "https://github.com/folke/tokyonight.nvim.git",
  "https://github.com/folke/trouble.nvim.git",
  "https://github.com/RRethy/vim-illuminate.git",
  "https://github.com/tpope/vim-repeat.git",
  "https://github.com/dstein64/vim-startuptime.git",
  "https://github.com/folke/which-key.nvim.git",
]
